name: arpes
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8

  - nomkl
  - astropy
  - xarray>=0.16.1
  - h5py>=3.2.1
  - pyqtgraph>=0.12.0,<0.13.0

  - pint
  - pandas

  - numpy>=1.20.0,<2.0.0
  - scipy>=1.6.0,<2.0.0
  - lmfit>=1.0.0,<2.0.0
  - netCDF4>=1.5.0,<2.0.0

  # plotting
  - colorcet
  - matplotlib>=3.0.3
  - bokeh>=2.0.0,<3.0.0
  - ipywidgets>=7.0.1,<8.0.0

  # Misc deps
  - pip

  # pip
  - pip:
      - PyQt5==5.15
      - packaging
      - numba>=0.53.0,<1.0.0
      - colorama
      - imageio
      - titlecase
      - tqdm
      - rx
      - dill
      - ase>=3.20.0,<4.0.0

      # documentation dependencies are basically only these
      - sphinx
      - sphinxcontrib-restbuilder
      - sphinx_rtd_theme
      - nbsphinx
      - sphinx_copybutton
      - -e .[core]
