channels:
  - conda-forge
dependencies:
  - python=3.8
  - nomkl

  - astropy
  - xarray>=0.16.1
  - h5py>=3.2.1

  - pint
  - pandas
  - numpy>=1.20.0,<2.0.0
  - scipy>=1.6.0,<2.0.0
  - lmfit>=1.0.0,<2.0.0
  - netCDF4>=1.5.0,<2.0.0
  - numba>=0.53.0,<1.0.0
  - pyqtgraph>=0.12.0,<0.13.0
  - ase>=3.17.0,<3.22.0

  # plotting
  - colorcet
  - matplotlib-base>=3.0.3
  - ipywidgets>=7.0.1,<8.0.0

  # Misc deps
  - packaging
  - colorama
  - imageio
  - tqdm
  - rx
  - dill